"""app.users + app.sessions: operator authentication

Revision ID: f4a5b6c7d8e9
Revises: e3f4a5b6c7d8
Create Date: 2026-05-23 14:00:00.000000

Operator authentication and the application-role model (design doc §3.10). These
are *application* roles layered on the single least-privileged stele_api
connection — they do NOT map to the Postgres roles of §3.3. Analyst/reviewer
*data* access stays a separate DB-credential concern (M3.5).

- app.users: an operator account. Password stored as an argon2id hash, never
  plaintext. role is constrained to the three application roles; disabled lets
  an account be locked without deletion (preserves FK history). email is unique
  and stored lowercased by the service so logins are case-insensitive.
- app.sessions: a server-side, revocable session. The opaque high-entropy token
  is the primary key; logout/expiry delete the row, so revocation is immediate
  (unlike a stateless JWT). ON DELETE CASCADE from users means disabling-then-
  deleting a user also drops their live sessions.

Grants. The schema-wide ALTER DEFAULT PRIVILEGES in the init SQL already give
stele_api SELECT/INSERT/UPDATE (+ sequence USAGE) on new app tables, which covers
user creation, login (insert session), and reading both. logout/expiry need
DELETE on app.sessions — granted here (table-specific grants can't ride the
create-later default-privilege inheritance; same rationale as the withdrawals
migration). stele_api gets DELETE on sessions only, never users (no user-deletion
path in M3.1).

Crucially this REVOKEs SELECT on both tables from stele_etl. The init SQL grants
stele_etl schema-wide SELECT on app (its ETL source), but password hashes and
session tokens must never reach the ETL role or the warehouse — dbt reads only
raw_responses (invariant 1/4), and these tables hold authentication secrets.
Least-privilege: the ETL role has no business reading them.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4a5b6c7d8e9"
down_revision: str | Sequence[str] | None = "e3f4a5b6c7d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("disabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.UniqueConstraint("email", name="uq_users_email"),
        # Application roles (design doc §3.10). Enforced in the DB so a bad write
        # can't introduce an unknown role that authz then has to guess about.
        sa.CheckConstraint("role IN ('admin', 'researcher', 'reviewer')", name="ck_users_role"),
        schema="app",
    )

    op.create_table(
        "sessions",
        # Opaque high-entropy token, generated by the service. Natural key.
        sa.Column("token", sa.Text(), primary_key=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name="fk_sessions_user",
            ondelete="CASCADE",
        ),
        schema="app",
    )
    # Revocation and expiry sweeps filter by user_id; index it.
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"], schema="app")

    # logout / session-revocation / expiry cleanup need DELETE on sessions only.
    op.execute("GRANT DELETE ON app.sessions TO stele_api")

    # Authentication secrets must never reach the ETL role or the warehouse.
    op.execute("REVOKE SELECT ON app.users, app.sessions FROM stele_etl")


def downgrade() -> None:
    op.execute("GRANT SELECT ON app.users, app.sessions TO stele_etl")
    op.execute("REVOKE DELETE ON app.sessions FROM stele_api")
    op.drop_index("ix_sessions_user_id", table_name="sessions", schema="app")
    op.drop_table("sessions", schema="app")
    op.drop_table("users", schema="app")
